### ISSUE TITLE
Hot Module Replacement (HMR) not working

### ISSUE THREAD

**Issue by ctaggart** [SAFE-Stack/SAFE-Nightwatch#50]
Hot Module Replacement is not working for me out of the box (with path changes in #49).

video coming...

**Comment by ctaggart** [comment]
YouTube video https://youtu.be/cTwNM-xJOBk

**Comment by ctaggart** [comment]
I tried updating Gradle and the Android plugin, but that didn't help. https://github.com/SAFE-Stack/SAFE-Nightwatch/pull/51

**Comment by ctaggart** [comment]
Any idea if https://github.com/facebook/react-native/issues/10991 is related? If so, could the babel-plugin-functional-hmr be used some how to [work around it](https://github.com/facebook/react-native/issues/10991#issuecomment-364037415)?

**Comment by ctaggart** [comment]
I tried updating to the latest react-native, but it had no impact. #52

**Comment by ctaggart** [comment]
One step closer, if I `Enable Hot Reloading` in the app by typing ctrl+m and selecting it, it does reload the app in the Android emulator. It actually says `Hot Loading` after I make a change, but the text change does not show up.

YouTube video update of this https://youtu.be/WVQl-HJ55C0

**Comment by forki** [comment]
ok let me check. with nightwatch. brb

**Comment by forki** [comment]
ok I can repro. Something regressed

**Comment by forki** [comment]
OMG. It broke in our production app as well.

**Comment by forki** [comment]
found a good commit 18 days ago in production app. now bisecting...

**Comment by forki** [comment]
ok good news and bad new:

good news: our production app master still works with HMR
bad news: I did not change anything

**Comment by forki** [comment]
OMG why did I see that earlier. 76f9c2a

**Comment by MangelMaxime** [comment]
Ah yes the lazyView problem with HMR...

Real question (no trolling) do you really use `lazyView` in your application ? I never used them, and my app seems fine like that.

**Comment by forki** [comment]
no I don't. but it was in the nightwatch sample.

**Comment by ctaggart** [comment]
Thanks for fixing this @forki! 🍻
