### ISSUE TITLE
fable-splitter package not installed

### ISSUE THREAD

**Issue by richardjharding** [SAFE-Stack/SAFE-Nightwatch#56]
I've cloned this out on two diff windows machines with the same result

after running build.cmd debug

The build fails at the CompileForTest target

The cause is that the fable-splitter package has not been installed

```
Finished Target: Restore
Starting Target: SetReleaseNotes (==> Restore)
Finished Target: SetReleaseNotes
Starting Target: SetVersionAndroid (==> SetReleaseNotes)
Finished Target: SetVersionAndroid
Starting Target: SetVersion (==> SetVersionAndroid)
Finished Target: SetVersion
Starting Target: CompileForTest (==> SetVersion)
C:\Users\richa\AppData\Local\dotnetcore\dotnet.exe  fable npm-run compile-for-test
Fable (1.3.8) daemon started on port 61225
CWD: D:\Source\Repos\SAFE-Nightwatch
cmd /C npm run compile-for-test

> nightwatch@1.0.0 compile-for-test D:\Source\Repos\SAFE-Nightwatch
> fable-splitter -c splitter.config.js --define TEST

'fable-splitter' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightwatch@1.0.0 compile-for-test: `fable-splitter -c splitter.config.js --define TEST`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nightwatch@1.0.0 compile-for-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\richa\AppData\Roaming\npm-cache\_logs\2018-03-22T16_41_28_382Z-debug.log
Closing Fable daemon...
Running build failed.
```

This is confirmed by examining the node_modules folder - in fact 

I've tried both yarn install and npm install - neither will install the dependency in this project

If I create a new folder , npm init and npm install --save-dev fable-splitter 

then it is installed and the correct .cmd file created in node_modules/.bin

As a result I don't think its my system but something in this config ?

Any suggestions on what I can check ?

I'm running 
node 6.11.0
npm 5.5.1

I see no errors during the yarn install thats run as part of the FAKE target

I'm able to create a new react-native app (non fable) and run ok I'm also able to create a new fable web app  - eg the Fable-elmish-react-demo app - but that doesn't use fable-splitter

**Comment by forki** [comment]
Maybe this was during nuget outtage?

Richard Harding <notifications@github.com> schrieb am Do., 22. März 2018,
17:46:

**Comment by richardjharding** [comment]
not sure - I've deleted node_modules and re-ran build.cmd and got the same result - I was still able to create a new folder and npm install fable-splitter in that - just doesn't get installed in this file structure during build
can't really see why

**Comment by richardjharding** [comment]
yep that sorted it - what am I missing - whats the connection between nuget packages and npm fable-splitter?

**Comment by richardjharding** [comment]
odd - its listed in package.json and gets added to node_modules and node_modules/.bin but cloning out again fresh worked - no idea

**Comment by forki** [comment]
Ok then I was wrong about it. But I still assume it was the outtage. Maybe
some other fable components were missing

Richard Harding <notifications@github.com> schrieb am Fr., 23. März 2018,
10:27:
